apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ include "temp.chart" . }}
spec:
  ports:
    - port: 2368
  selector:
    app: {{ .Release.Name }}
    release: {{ .Release.Name }}
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pv-claim
  labels:
    app: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ include "temp.chart" . }}
spec:
  selector:
    matchLabels:
    app: {{ .Release.Name }}
    release: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: ghost
        ports:
        - containerPort: 2368
        volumeMounts:
        - name: {{ .Release.Name }}-persistent-storage
          mountPath: /var/lib/ghost/content
      volumes:
      - name: {{ .Release.Name }}-persistent-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pv-claim
