# Default values for helm_chart_creation.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
storage: 10Gi

image:
  repo: ghost
  tag: stable

pod:
  port: 2368

nameOverride: ""
fullnameOverride: ""

service:
  enabled: false
  tier: Frontend 
  type: LoadBalancer
  port: 2368

deployments:
  all_apps: 
   - api
   - chat

api:
  relicacoun: 3 
