{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ include "temp.chart" . }}
spec:
  ports:
    - port: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}
    release: {{ .Release.Name }}
    tier: {{ .Values.service.tier }}
  type: {{ .Values.service.port }}
{{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pv-claim
  labels:
    app: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage }}
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ include "temp.chart" . }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      release: {{ .Release.Name }}
  replicas: {{ .Values[index].replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Valuesmage.repo }}
        ports:
        - containerPort: {{ .Values.pod.port }}
        volumeMounts:
        - name: {{ .Release.Name }}-persistent-storage
          mountPath: /var/lib/ghost/content
      volumes:
      - name: {{ .Release.Name }}-persistent-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pv-claim
