apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-content-pv
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/{{ .Release.Name }}-content-pv
